### ISSUE TITLE
bug: date-picker dropdown requires a second click after selection in order to update the search.

### ISSUE THREAD

**Issue by danielsgriffin** [devflowinc/trieve-hn-discovery#100]
### Description

Conduct a search. Click the date-picker for the date range. Select a range. 

Expectation: Selecting range updates the results.

Click the input again to update the results.

https://github.com/user-attachments/assets/320c4787-7f5f-49c7-8053-0e5e2bf6e5f7

### Target(s)

Search.

### Requirement to close

PR with selection driving the updated results.

### Community channels

Matrix is preferred. Reach out on discord or Matrix for further assistance. 

- [discord](https://discord.gg/CuJVfgZf54)
- [matrix](https://matrix.to/#/#trieve-general:trieve.ai)

**Comment by skeptrunedev** [comment]
I can't replicate this. My suspicion is that it was due to high network latency and just seemed like a second click was required when it was actually just loading. 

The `animate-pulse` on load should help show this now. If it can be repro'd please open again.
