### ISSUE TITLE
bug: score threshold for fulltext and bm25 search do not match the range in the label

### ISSUE THREAD

**Issue by danielsgriffin** [devflowinc/trieve-hn-discovery#105]
### Description

Click Advanced dropdown, look at the Score threshold label vs. default for Fulltext:
Label: `Score Threshold (0.0 to 1.0):`
Default: `5`

<img width="999" alt="image" src="https://github.com/user-attachments/assets/3039f68b-d8b6-4237-b767-eb28e4869fac">

See relevant UI code in `Filters.tsx`:

```
<div class="flex items-center justify-between space-x-2 whitespace-nowrap p-1">
                <label>Score Threshold (0.0 to 1.0):</label>
                <input
                  class="w-16 rounded border border-neutral-400 p-0.5 text-black"
                  type="number"
                  step="any"
                  value={props.searchOptions.scoreThreshold ?? 0}
                  onChange={(e) => {
                    props.setSearchOptions(
                      "scoreThreshold",
                      e.target.valueAsNumber,
                    );
                  }}
                />
              </div>
```

The key issue is that fulltext search in SPLADE is not normalized and the score can vary considerably.

For instance, the best match docs for these two searches are  118.433 and 9.923.
[[They don't mention BM25, which still outperforms much of semantic search. A fun exercise is to watch the benchmarks of the latest semantic embeddings models and see that they still struggle to match good 'ol BM25. BM25 uses the relative statistical frequency of words to identify relevant material, along with some adjustments. It doesn't use ML at all, but it works very well, especially for technical content.  SPLADE is capable for some areas but is slow, and often times it doesn't present much of a benefit (or is worse) versus BM25 for technical searches, where specific technical words don't have many synonyms that it would be able to pull.  The best search systems today use a mix of semantic search and BM25 or SPLADE, depending on the type of material and the speed required.]](https://hn.withtrieve.com/?q=They+don%27t+mention+BM25%2C+which+still+outperforms+much+of+semantic+search.+A+fun+exercise+is+to+watch+the+benchmarks+of+the+latest+semantic+embeddings+models+and+see+that+they+still+struggle+to+match+good+%27ol+BM25.+BM25+uses+the+relative+statistical+frequency+of+words+to+identify+relevant+material%2C+along+with+some+adjustments.+It+doesn%27t+use+ML+at+all%2C+but+it+works+very+well%2C+especially+for+technical+content.++SPLADE+is+capable+for+some+areas+but+is+slow%2C+and+often+times+it+doesn%27t+present+much+of+a+benefit+%28or+is+worse%29+versus+BM25+for+technical+searches%2C+where+specific+technical+words+don%27t+have+many+synonyms+that+it+would+be+able+to+pull.++The+best+search+systems+today+use+a+mix+of+semantic+search+and+BM25+or+SPLADE%2C+depending+on+the+type+of+material+and+the+speed+required.&score_threshold=5&page_size=30&prefetch_amount=30&rerank_type=none&highlight_delimiters=frankly&highlight_threshold=0.85&highlight_max_length=50&highlight_max_num=50&highlight_window=0&recency_bias=0&highlight_results=true&use_quote_negated_terms=true&storyType=comment&matchAnyAuthorNames=&matchNoneAuthorNames=&popularityFilters=%7B%7D&sortby=Relevance&dateRange=all&searchType=fulltext&page=1)

[["lootitooti"]](https://hn.withtrieve.com/?q=%22lootitooti%22&score_threshold=5&page_size=30&prefetch_amount=30&rerank_type=none&highlight_delimiters=frankly&highlight_threshold=0.85&highlight_max_length=50&highlight_max_num=50&highlight_window=0&recency_bias=0&highlight_results=true&use_quote_negated_terms=true&storyType=comment&matchAnyAuthorNames=&matchNoneAuthorNames=&popularityFilters=%7B%7D&sortby=Relevance&dateRange=all&searchType=fulltext&page=1)

### Target(s)

<replace w/ one or more of the following options: `server`, `search`, `chat`>

### Requirement to close

PR that dynamically updates the score threshold range based on the search type.

Perhaps an information icon could be added to the threshold label for fulltext/SPLADE that provides a small popup explanation, something like.
"The scores in SPLADE fulltext search are not normalized. Due to how ranking scores are calculated, the range of threshold scores for SPLADE are context-dependent and may require tuning based on the specific retrieval requirements."

### Community channels

Matrix is preferred. Reach out on discord or Matrix for further assistance. 

- [discord](https://discord.gg/CuJVfgZf54)
- [matrix](https://matrix.to/#/#trieve-general:trieve.ai)

**Comment by skeptrunedev** [comment]
Wish I fixed before launch, but done now!
