### ISSUE TITLE
bug: unexpected behavior with site: operator subdomain and protocol variations

### ISSUE THREAD

**Issue by danielsgriffin** [devflowinc/trieve-hn-discovery#128]
## Issue
The `site:` search operator produces inconsistent results when used with different URL formats of the same domain.

## Examples
1. `site:theguardian.com` - Returns results
2. `site:www.theguardian.com` - Returns different results from #1
3. `site:https://www.theguardian.com` and `site:https://theguardian.com` - Returns no results

## Expected Behavior
All variations should return the same set of results, as they refer to the same website (though perhaps some distinctions exist in the www subdomain and http/https protocols may indicate distinct patterns that the searcher wants to distinguish).

## Actual Behavior
- Different URL formats produce different result sets
- Including the full URL with protocol returns no results

## Impact
- Incomplete or inconsistent search results
- User confusion and potential missed information

## Suggested Fix
Normalize URLs by stripping protocols and subdomains before processing the `site:` operator search.
OR providing clarifying note.

**Comment by skeptrunedev** [comment]
Agreed. `www` should be a special case during ingest where we create both a tag with and without it
