### ISSUE TITLE
feature: use count route to show the total count of matches 

### ISSUE THREAD

**Issue by skeptrunedev** [devflowinc/trieve-hn-discovery#23]
We now have a dedicated route - https://docs.trieve.ai/api-reference/chunk/count-chunks-above-threshold - for getting the count of chunks above a threshold for search which we should use to display count of results. 

Set a limit of `100,000` on the call and if the count is `100,000` on the response then display "100,000+". 

Algolia has it as follows - 
![image](https://github.com/devflowinc/hn_frontend/assets/15804464/119ce8d1-caa4-409f-b5c0-ed63de4959ac)

For us it should go here - 
![image](https://github.com/devflowinc/hn_frontend/assets/15804464/12733a16-a11e-4714-a58c-ac59f9502cc3)

**Comment by varshith257** [comment]
/attempt #23

<div id="algora-attempt" />

| [Algora profile](https://console.algora.io/@/varshith257) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @varshith257 | &nbsp;&nbsp;&nbsp;1 trieve bounty <br/> + 4 bounties from 2 projects | <div align="center">TypeScript, Go</div> | <div align="center"></div> | [Cancel attempt](https://console.algora.io/api/bounties/clyg90ov20002ml09gbol7jbt/cancel-attempt) |

**Comment by skeptrunedev** [comment]
This requires an admin api key which has more perms than that which is in the dist. Ping on discord or Matrix for an API key with increased perms if you are working on this issue!

**Comment by skeptrunedev** [comment]
Closing this bounty because the route can be extremely high latency for high limits or low thresholds and would open the server up to abuse.
