### ISSUE TITLE
feature: show the latency of the query in the UI

### ISSUE THREAD

**Issue by skeptrunedev** [devflowinc/trieve-hn-discovery#25]
On the search route, we return the latency of the query for each component in the timing headers and we should display the sum of these: 

![image](https://github.com/devflowinc/hn_frontend/assets/15804464/71882d73-3fd4-4635-b777-988da6928257)

The end result should look similar to what Algolia does:

![image](https://github.com/devflowinc/hn_frontend/assets/15804464/1f89055f-8b5e-4607-8260-4b02eae10cc8)

**Comment by Gmin2** [comment]
hello
