### ISSUE TITLE
enhancement: add back recommendations

### ISSUE THREAD

**Issue by densumesh** [devflowinc/trieve-hn-discovery#48]
Right now recommendations are disabled, but we should reenable and fix the issues before release.

**Comment by Bhavyajain21** [comment]
Hey @densumesh , can I be assigned on this?

**Comment by densumesh** [comment]
Yes of course! Feel free to reach out with questions

**Comment by skeptrunedev** [comment]
Rough design sketch:

![image](https://github.com/user-attachments/assets/668adb11-159a-49d7-a119-adb75f923018)

**Comment by skeptrunedev** [comment]
I changed my mind. Going to make the modal simple and create a new page for more complex recs

**Comment by skeptrunedev** [comment]
Completed in #61
