### ISSUE TITLE
feature: change bulk_ingest.py to include `boost_phrase` to move stories closer to the title

### ISSUE THREAD

**Issue by cdxker** [devflowinc/trieve-hn-discovery#51]
Some experimentation is needed here, we need a good value of how hard we should push values towards each other.

The main idea is to have `splade` and `semantic` search bias stories a little bit more. This would be a slight improvement over the `weight` system as it is able to fetch from a different page.

**Comment by densumesh** [comment]
Can we not use tag_weight to weight stories higher in the search results?
