### ISSUE TITLE
feature: include a short description of each search type in the FAQ

### ISSUE THREAD

**Issue by fedhacks** [devflowinc/trieve-hn-discovery#81]
### Description

It's really cool that we're offering all 4 flavors of search for folks to try out. 

Let's educate the general public on what each of these search types are at a relatively high level. These descriptions may be enriched with links to write ups in the future too

### Target(s)

'FAQ'

### Requirement to close

<please describe what is required to close this issue here>

### Community channels

Matrix is preferred. Reach out on discord or Matrix for further assistance. 

- [discord](https://discord.gg/CuJVfgZf54)
- [matrix](https://matrix.to/#/#trieve-general:matrix.zerodao.gg)

**Comment by SaraVieira** [comment]
This is already done no?
