### ISSUE TITLE
feature: isolate and feature the posted by user(s)

### ISSUE THREAD

**Issue by fedhacks** [devflowinc/trieve-hn-discovery#82]
### Description

This is a standout feature we offer. You can know target accounts when you get angry with them by offering search by author. 

Also, I strongly believe this should be **posted by user(s)** instead of **author** since that tracks with what HN calls posters. 

### Target(s)

'filters'

![Screenshot 2024-07-31 at 11 10 44 PM](https://github.com/user-attachments/assets/e4176040-2c5e-4a9d-a8d8-2f3fd2996dc3)

### Requirement to close

<please describe what is required to close this issue here>

### Community channels

Matrix is preferred. Reach out on discord or Matrix for further assistance. 

- [discord](https://discord.gg/CuJVfgZf54)
- [matrix](https://matrix.to/#/#trieve-general:matrix.zerodao.gg)

**Comment by skeptrunedev** [comment]
Done :heavy_check_mark:
