### ISSUE TITLE
feature: add "information" icon as activation that links to FAQ on the types of search

### ISSUE THREAD

**Issue by fedhacks** [devflowinc/trieve-hn-discovery#83]
### Description

"What is Splade? What is BM25? What is Hybrid?" - 95% of people who will land on the site 

"I'm going to google to learn more about these search types" - a *very* small % of the 95%

"I'm going to click this information icon to learn more" - a *very* significant % of the 95%

![image](https://github.com/user-attachments/assets/32caaf3d-4951-42b4-a66f-8c7db0dc0bce)

### Target(s)

'filters'

![Screenshot 2024-07-31 at 11 15 13 PM](https://github.com/user-attachments/assets/41d3fbe9-ec06-44e0-98e2-e5e37c4f5ce1)

### Requirement to close

<please describe what is required to close this issue here>

### Community channels

Matrix is preferred. Reach out on discord or Matrix for further assistance. 

- [discord](https://discord.gg/CuJVfgZf54)
- [matrix](https://matrix.to/#/#trieve-general:matrix.zerodao.gg)

**Comment by skeptrunedev** [comment]
Punted in preference for including in the about page and help modal
