### ISSUE TITLE
bug: search and scroll does not work when searching by popularity or date

### ISSUE THREAD

**Issue by fedhacks** [devflowinc/trieve-hn-discovery#85]
### Description

Searching by popularity or date on all modes except hybrid

Here's complicated way to replicate the bug:

1) query anything 

<img width="612" alt="Screenshot 2024-08-04 at 6 40 19 PM" src="https://github.com/user-attachments/assets/63f63ede-1df1-4db4-9f90-4eb0d1dd0793">

[duterte mass murderer and trump](https://hn.withtrieve.com/score_threshold=5&page_size=30&prefetch_amount=30&rerank_type=none&highlight_delimiters=+,-,_,.,,&highlight_threshold=0.85&highlight_max_length=50&highlight_max_num=50&highlight_window=0&recency_bias=0&highlight_results=true&use_quote_negated_terms=true&q=duterte+mass+murderer+and+trump&storyType=all&authorNames=&sortby=Relevance&dateRange=all&searchType=fulltext&page=1) 

2) change sort relevance to "popularity"

[same query but sort by changed to popularity](https://hn.withtrieve.com/?score_threshold=5&page_size=30&prefetch_amount=30&rerank_type=none&highlight_delimiters=+,-,_,.,,&highlight_threshold=0.85&highlight_max_length=50&highlight_max_num=50&highlight_window=0&recency_bias=0&highlight_results=true&use_quote_negated_terms=true&q=duterte+mass+murderer+and+trump&storyType=all&authorNames=&sortby=Popularity&dateRange=all&searchType=fulltext&page=1)

3) modify/delete query to see search and saty not work 

[duterte visits america](https://hn.withtrieve.com/?score_threshold=5&page_size=30&prefetch_amount=30&rerank_type=none&highlight_delimiters=+,-,_,.,,&highlight_threshold=0.85&highlight_max_length=50&highlight_max_num=50&highlight_window=0&recency_bias=0&highlight_results=true&use_quote_negated_terms=true&q=duterte+visits+america&storyType=all&authorNames=&sortby=Popularity&dateRange=all&searchType=fulltext&page=1)

If you delete the whole query it will reset but search and saty will still not work
<img width="622" alt="Screenshot 2024-08-04 at 6 41 23 PM" src="https://github.com/user-attachments/assets/aa372b14-53a3-4832-9d3e-bc1daad9d8f8">
[Link](https://hn.withtrieve.com/?score_threshold=5&page_size=30&prefetch_amount=30&rerank_type=none&highlight_delimiters=+,-,_,.,,&highlight_threshold=0.85&highlight_max_length=50&highlight_max_num=50&highlight_window=0&recency_bias=0&highlight_results=true&use_quote_negated_terms=true&q=&storyType=all&authorNames=&sortby=Popularity&dateRange=all&searchType=fulltext&page=1)

### Target(s)

'search'

### Requirement to close

<please describe what is required to close this issue here>

### Community channels

Matrix is preferred. Reach out on discord or Matrix for further assistance. 

- [discord](https://discord.gg/CuJVfgZf54)
- [matrix](https://matrix.to/#/#trieve-general:trieve.ai)

**Comment by skeptrunedev** [comment]
fixed via server updates
