### ISSUE TITLE
bug: fix homepage scroll 

### ISSUE THREAD

**Issue by fedhacks** [devflowinc/trieve-hn-discovery#86]
### Description

Let's fix scroll so this is correct 

Qdrant or postgres?

<img width="499" alt="Screenshot 2024-08-04 at 6 56 23 PM" src="https://github.com/user-attachments/assets/e9f318ee-100a-48ff-8275-47b1022ac7d7">

### Target(s)

'search'

### Requirement to close

<please describe what is required to close this issue here>

### Community channels

Matrix is preferred. Reach out on discord or Matrix for further assistance. 

- [discord](https://discord.gg/CuJVfgZf54)
- [matrix](https://matrix.to/#/#trieve-general:trieve.ai)

**Comment by skeptrunedev** [comment]
fixed now
