### ISSUE TITLE
enhancement: rate limits

### ISSUE THREAD

**Issue by fedhacks** [devflowinc/trieve-hn-discovery#88]
### Description

let's add rate limiting

### Target(s)

'search', 'server'

### Requirement to close

<please describe what is required to close this issue here>

### Community channels

Matrix is preferred. Reach out on discord or Matrix for further assistance. 

- [discord](https://discord.gg/CuJVfgZf54)
- [matrix](https://matrix.to/#/#trieve-general:trieve.ai)

**Comment by skeptrunedev** [comment]
Will do if needed. Otherwise let people have at it!
