### ISSUE TITLE
bug: Proper routing for sub pages 

### ISSUE THREAD

**Issue by cdxker** [devflowinc/trieve-hn-discovery#89]
Navigating directly to https://hn.withtrieve.com/chat responds with 404.

Where as clicking the button does not 404.

**Comment by skeptrunedev** [comment]
Seems to be caddy. Going to try and fix

**Comment by skeptrunedev** [comment]
Solved! 

Github gist for future reference - https://gist.github.com/skeptrunedev/fbacead2632d9216bbff3ef5629dcccb
