### ISSUE TITLE
bug: page links appear even when there is only one page of results

### ISSUE THREAD

**Issue by danielsgriffin** [devflowinc/trieve-hn-discovery#96]
### Description

Here is a search for ["silly query"](https://hn.withtrieve.com/?q=%22silly+query%22&score_threshold=5&page_size=30&prefetch_amount=30&rerank_type=none&highlight_delimiters=+%2C-%2C_%2C.%2C%2C&highlight_threshold=0.85&highlight_max_length=50&highlight_max_num=50&highlight_window=0&recency_bias=0&highlight_results=true&use_quote_negated_terms=true&storyType=story&authorNames=&sortby=Relevance&dateRange=all&searchType=fulltext&page=1)

<img width="1221" alt="image" src="https://github.com/user-attachments/assets/af4b2526-d627-4f16-88c9-133b0c4193a2">

Clicking the button to go to the second page shows "No stories found"

### Target(s)

`search`

### Requirement to close

PR that:

- removes page buttons if only one page of results.

### Community channels

Matrix is preferred. Reach out on discord or Matrix for further assistance. 

- [discord](https://discord.gg/CuJVfgZf54)
- [matrix](https://matrix.to/#/#trieve-general:trieve.ai)

**Comment by skeptrunedev** [comment]
This one is moderately complex as there will need to be an additional API call to https://docs.trieve.ai/api-reference/chunk/count-chunks-above-threshold to figure out how many pages there should be. 

That call should be in an effect which only runs if the `query` or `scoreThreshold` params change and nothing else.
