### ISSUE TITLE
bug: back button skips app history, exits to last page load instead of navigating to previous 'page'

### ISSUE THREAD

**Issue by danielsgriffin** [devflowinc/trieve-hn-discovery#98]
### Description

The browser's back button is not functioning as expected. When pressed, it goes back to the last full page load in the browser instead of navigating to the previous rendered page view within the app, despite the URL changing during navigation.

Steps to Reproduce:
1. Go to https://hn.withtrieve.com/
2. Search [test], Scroll to the bottom and click the button for page 2, click the button for page 3.
3. Press the browser's back button

Expected Behavior: The back button should navigate to the previous page view within the app (i.e. page 2), following the app's navigation history.

Actual Behavior: The back button exits the app completely, returning to whatever page (or a blank tab if none) you had loaded before entering the app.

### Target(s)

window.history OR solidJS Router?

### Requirement to close

PR which integrates with the browser's History API such that the back and forward buttons navigate to the appropriate pages within the app

### Community channels
Matrix is preferred. Reach out on discord or Matrix for further assistance. 
- [discord](https://discord.gg/CuJVfgZf54)
- [matrix](https://matrix.to/#/#trieve-general:trieve.ai)

**Comment by skeptrunedev** [comment]
I need to do more research into this. Spent a short while trying to fix and determined it's a browser thing where it doesn't save new URL params as history entries.
